import Head from "next/head";
import Image from "next/image";
import Landing from "../components/sections/Landing/Landing";
import FixedSection from "../components/sections/FixedSection/FixedSection";
import NewEdition from "../components/sections/NewEdition/NewEdition";
import Models from "../components/sections/Models/Models";
import styles from "../styles/Index.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing />
      <FixedSection />
    </div>
  );
}
